# Generated by Django 5.2.14 on 2026-05-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Question')),
                ('choice_a', models.CharField(max_length=255, verbose_name='Choice A')),
                ('choice_b', models.CharField(max_length=255, verbose_name='Choice B')),
                ('choice_c', models.CharField(max_length=255, verbose_name='Choice C')),
                ('choice_d', models.CharField(max_length=255, verbose_name='Choice D')),
                ('rrect_answer', models.CharField(choices=[('A', 'Choice A'), ('B', 'Choice B'), ('C', 'Choice C'), ('D', 'Choice D')], help_text='Select the correct option', max_length=1)),
            ],
        ),
    ]
