# Generated by Django 5.2.14 on 2026-05-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqquestion',
            name='rrect_answer',
            field=models.CharField(choices=[('choice_a', 'A'), ('choice_b', 'B'), ('choice_c', 'C'), ('choice_d', 'D')], help_text='Select the correct option', max_length=10),
        ),
    ]
