# Generated by Django 5.2.14 on 2026-05-18 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0002_alter_mcqquestion_rrect_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcqquestion',
            old_name='rrect_answer',
            new_name='correct_answer',
        ),
    ]
